### PR TITLE
Removes null terminators from Rust strings.

### PR DESCRIPTION
**Pull request by remexre**
Refer https://github.com/cogciprocate/ocl/issues/48.

### CODE REVIEW

**Comment by c0gent** [comment]
Looks great. That's almost certainly the cleanest way to do it.

I'm still not sure this is something that this library should be concerned with. The minimalist inside me insists that this should be left to the user. There may, after all, be some yet unknown use to leaving the nulls in place. Someone exporting those strings would be a fool not to remove whichever characters are invalid for the destination format anyway.

Please convince me otherwise.

**Comment by remexre** [comment]
> Someone exporting those strings would be a fool not to remove whichever characters are invalid for the destination format anyway.
Then serde is a fool? Null terminators aren't invalid, they're properly escaped. But they're definitely not what anyone meant. I'll write a real-world example in a couple minutes.

**Comment by c0gent** [comment]
> Someone exporting those strings would be a fool not to remove whichever characters are invalid for the destination format anyway.

Well yeah, I meant handle rather than remove.

As far as I can remember, Serde, and any other serialization libraries handle nulls just fine.

Again, I'm happy to implement your changes I just want to make sure that doing so doesn't solve a problem that isn't really a problem. I'm basically leaning 51%/49% in your direction at the moment.

I'll await your example and thanks for your time :)

**Comment by remexre** [comment]
The main thing I came up with is that if I had something like https://gist.github.com/remexre/45eb6fa95918917be0b7cb0e4244b6d2 on a whole bunch of devices I SSH'd to, then tried doing string-matching against them, it'd get weird results for no reason. Doubly or triply so if it got interchanged between a format with fewer escapes: e.g. `\0` isn't illegal in CSV, but how much would you bet that a majority of CSV parsers written in C would properly handle it?

> [Be conservative in what you send, be liberal in what you accept.](https://en.wikipedia.org/wiki/Robustness_principle)

**Comment by c0gent** [comment]
Makes sense to me. I can't think of any reason to preserve those nulls anyway. I'll merge sometime soon. 

Thanks again.

**Pull request merged**
