### PR TITLE
Basic GLX sharing support

### PR DESCRIPTION
**Pull request by YaLTeR**
Added some missing setters, pretty straightforward. See https://github.com/cogciprocate/ocl/issues/23.

### CODE REVIEW

**Comment by c0gent** [comment]
Sorry I took so long to merge :)

**Comment by c0gent** [comment]
By the way, I made the other changes to [`ContextBuilder`](http://10.0.0.11/ocl/ocl/builders/struct.ContextBuilder.html#method.glx_display) as well.

**Comment by YaLTeR** [comment]
That's a local IP url. :P

**Comment by c0gent** [comment]
Heh, sorry about that :)

http://doc.cogciprocate.com/ocl/ocl/builders/struct.ContextBuilder.html#method.glx_display

**Comment by YaLTeR** [comment]
Seems to work well!

**Pull request merged**
