### PR TITLE
Tests for ocl-core

### PR DESCRIPTION
**Pull request by Kerosene2000**
- [ ] kernel_arg_ptr
- [ ] buffer_ops_rect
- [ ] image_ops
- [ ] clear_completed
- [ ] concurrent
- [ ] vector_types
- [ ] context_props
- [x] build_error
- [x] buffer_copy
- [x] buffer_fill

### CODE REVIEW

**Comment by c0gent** [comment]
Looks great!

**Comment by Kerosene2000** [comment]
just to know, can I push again on this PR and you can merge again ?

**Comment by c0gent** [comment]
Yeah I was going to ask you if you wanted me to leave it unmerged until you were done... I'd just go ahead and create a new one and I'll leave that new one open.

**Comment by Kerosene2000** [comment]
ok 👍

**Comment by c0gent** [comment]
Nice work btw.

**Comment by Kerosene2000** [comment]
Then on this branch I can push and you can merge until this is done ?

**Comment by c0gent** [comment]
I don't know if that will work but you can try.

If it does not, make a new pull request then copy and paste your checklist above.

**Pull request merged**
